### ISSUE TITLE
Attach system-tools diagnostics to a support ticket

### ISSUE THREAD

**Issue by dnoland1** [rancher/system-tools#13]
Would be great when running system-tools you can pass a support ticket number and it would attach the diagnostics to a support ticket.

**Comment by jiaqiluo** [comment]
The issue is moved to rancher/rancher  https://github.com/rancher/rancher/issues/20920

Should you have new issues found for system-tool, please log the issue under rancher/rancher
https://github.com/rancher/rancher/issues

**Comment by dnoland1** [comment]
Sure, will do that in the future.
