### ISSUE TITLE
expand the info and logs collected by system tools

### ISSUE THREAD

**Issue by aemneina** [rancher/system-tools#16]
It would be awesome to integrate this scripts capabilities into parts of system tools log collection:
https://gist.github.com/superseb/6c57c123680e14c2551856fe707b6493

We use this today in an ad hoc manner per node on k8s clusters (management or user).

**Comment by jiaqiluo** [comment]
This issue is moved and tracked under rancher/rancher https://github.com/rancher/rancher/issues/20917

Should you have new issues found for system-tool, please log the issue under rancher/rancher
https://github.com/rancher/rancher/issues
